<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Framework\View\Element\Template $block */
?>

<div class="add-to-cart-success-message">
    <?= $block->escapeHtml(__(
        'You added %1 to your <a href="%2">shopping cart</a>. <div class="close-message-success">x</div>',
        $block->getData('product_name'),
        $block->getData('cart_url')
    ), ["a", "div"]); ?>
</div>
