<?php
/**
 * @var $block BoonMarket\PhotoGallerySec\Block\Widget\PhotoGallerySecBlock
 */
?>

<section class="section7">
    <h2><?= $block->getSecTitle() ?></h2>
    <div class="section7__gallery">
        <img src="<?= $block->getImage1() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage2() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage3() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage4() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage5() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage6() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage7() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage8() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage9() ?>" alt="" class="section7__img">
        <img src="<?= $block->getImage10() ?>" alt="" class="section7__img">
    </div>
</section>
