<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="title"><strong><?php /* @escapeNotVerified */ echo __('Newsletter') ?></strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()); ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field firstname">
                <label class="label" for="firstname"><span><?php echo $block->escapeHtml(__('First name')) ?></span></label>
                <div class="control">
                    <input name="firstname" type="text" id="firstname" placeholder="<?php echo $block->escapeHtml(__('First name')) ?>" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php echo $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter" placeholder="<?php echo $block->escapeHtml(__('Email address')) ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('go')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
